# Generated by Django 5.2.17 on 2026-08-04 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('variations', models.TextField(blank=True, help_text='Variações separadas por linha')),
                ('answer', models.TextField()),
                ('source_title', models.CharField(max_length=200)),
                ('source_url', models.URLField(blank=True)),
                ('reviewed_at', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='knowledge.knowledgecategory')),
            ],
            options={
                'verbose_name': 'Item de conhecimento',
                'verbose_name_plural': 'Itens de conhecimento',
            },
        ),
    ]
